### ISSUE TITLE
Improvement - VBA Scripts

### ISSUE THREAD

**Issue by cristianbuse** [edugca/xlMATRIX#2]
I think it would be a great improvement to have 2 VBA scripts:
1) to read the existing named ranges (lambdas) and write them to a text file (e.g. json or xml) where you clearly have the name and formula for each lambda
2) to read the text file and create the named ranges

Advantages:
1) The text file containing the lamba formulas would clearly show the differences between commits
2) Not all people trust downloading an Excel workbook, but everyone trusts text files. Transparency
3) Lambas can be inserted into any existing book just by running the second script. No need to open the current demo book and manually copy lambdas
4) The script that reads the text file can pop-up a dialog and allow the users to choose only some of the lambdas or all of them (listbox multi-choice). Of course there are some dependencies between lambas but you can have grouping
5) Others can contribute more easily by updating the text file and you would immediately see the changes and be able to approve their pull requests
6) This repo would still be "no VBA" because the scripts are just one-time use tools to make life easier

**Comment by edugca** [comment]
Hi Cristian,

Thanks for the comments!

With respect to (1), there is a VBA procedure called ExportAllLambdasAsGists within the workbook that does that. These text files are called Gists. Whenever I update xlMATRIX, I update that text file as well. It is available on the link below: 

[https://gist.github.com/edugca/5cf477673b7d8c76431ed9f52c09f7e7](https://gist.github.com/edugca/5cf477673b7d8c76431ed9f52c09f7e7)

Concerning (2), this can be done with "Excel Labs". It is an add-in that provides a text editor for writing lambda functions. It also allows one to read all Lambda functions from a Gist file. You simply need to specify the link above, and it will create all lambda functions as named ranges.

All the best,
Eduardo

**Comment by cristianbuse** [comment]
HI Eduardo,

Thanks for getting back!

Did not realize there was a macro in the workbook. Apologies about that - I only glanced through.

Is there any reason why you would keep the formulas in a gist rather than in this repository? I suspect your answer will be because of Excel Labs but it seems odd they wouldn't be able to load a file from a git repository rather then a gist.

My company policy does not allow users to install add-ins. This is a common thing in large corporate. Hence, my suggestion.

All the best,
Cristian
